"""
Django settings for dict project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from dotenv import load_dotenv
load_dotenv()
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-63q9h(znz#1e)m&74w9#_n5nakdb!qx*fqhfi=&k7e3bwmaia$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['lumendeo-production.up.railway.app','127.0.0.1','lumendeo.tv']
CSRF_TRUSTED_ORIGINS=['https://lumendeo-production.up.railway.app','https://127.0.0.1','https://lumendeo.tv']


LOGIN_URL = '/admin/login/'  # Where to redirect when login is required
LOGIN_REDIRECT_URL = '/dashboard/'  # Where to go after successful login
LOGOUT_REDIRECT_URL = '/'  # Where to go after logout


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'myapp',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pwa',
    # 'storages',  # REMOVED: We're using local storage now
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'dict.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR,'template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dict.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
       'NAME':  BASE_DIR/'db.sqlite3',
        
    }
}
#DATABASE_URL = 'postgresql://postgres:RhegLImGJrFtUhEvBJtsEOuRuvWmCDwe@ballast.proxy.rlwy.net:49109/railway'

#import dj_database_url
#DATABASES['default'] = dj_database_url.parse(DATABASE_URL, conn_max_age=1800)


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ================================================
# LOCAL MEDIA STORAGE (NO S3)
# ================================================
MEDIA_URL = '/media/'  # URL for accessing media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Directory to store media

# Create media directories if they don't exist
os.makedirs(os.path.join(MEDIA_ROOT, 'videos'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'trailers'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'thumbnails'), exist_ok=True)

# Allow up to 5 GB for video uploads
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024 * 1024  # 5 GB in bytes
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024 * 1024  # 5 GB in bytes

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ================================================
# REMOVED S3 SETTINGS - USING LOCAL STORAGE INSTEAD
# ================================================

# Commented out all AWS S3 settings:
# AWS_ACCESS_KEY_ID = 'AKIA3EQ3LS2YIFVNU5EA'
# AWS_SECRET_ACCESS_KEY = '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'
# AWS_STORAGE_BUCKET_NAME = 'my-django-media-buckets'
# AWS_REGION = 'eu-north-1'

# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# AWS_S3_FILE_OVERWRITE = False
# AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
# MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/'

# ================================================
# PWA Settings
# ================================================

PWA_APP_NAME = 'LUMENDEO tv'
PWA_APP_DESCRIPTION = "A Christian based movie site"
PWA_APP_THEME_COLOR = '#000000'
PWA_APP_BACKGROUND_COLOR = '#000000'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'portrait'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/img/web-app-manifest-192x192.png',
        'sizes': '192x192'
    },
    {
        'src': '/static/img/web-app-manifest-512x512.png',
        'sizes': '512x512'
    }
]
PWA_APP_ICONS_APPLE = [
{
        'src': '/static/img/web-app-manifest-192x192.png',
        'sizes': '192x192'
    },
    {
        'src': '/static/img/web-app-manifest-512x512.png',
        'sizes': '512x512'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'